import GithubService from '../../services/GithubService';

export function addRepositories(login) {
    return async (dispatch) => {
        try {
            const repositories = await GithubService.getRepositoriesByName(login);
            dispatch({
                type: "ADD_REPOSITORIES",
                payload: repositories
                // payload: [
                //     {
                //         "id": 112770020,
                //         "node_id": "MDEwOlJlcG9zaXRvcnkxMTI3NzAwMjA=",
                //         "name": "deploy-teste",
                //         "full_name": "yuriyago/deploy-teste",
                //         "private": false,
                //         "owner": {
                //             "login": "yuriyago",
                //             "id": 18572853,
                //             "node_id": "MDQ6VXNlcjE4NTcyODUz",
                //             "avatar_url": "https://avatars2.githubusercontent.com/u/18572853?v=4",
                //             "gravatar_id": "",
                //             "url": "https://api.github.com/users/yuriyago",
                //             "html_url": "https://github.com/yuriyago",
                //             "followers_url": "https://api.github.com/users/yuriyago/followers",
                //             "following_url": "https://api.github.com/users/yuriyago/following{/other_user}",
                //             "gists_url": "https://api.github.com/users/yuriyago/gists{/gist_id}",
                //             "starred_url": "https://api.github.com/users/yuriyago/starred{/owner}{/repo}",
                //             "subscriptions_url": "https://api.github.com/users/yuriyago/subscriptions",
                //             "organizations_url": "https://api.github.com/users/yuriyago/orgs",
                //             "repos_url": "https://api.github.com/users/yuriyago/repos",
                //             "events_url": "https://api.github.com/users/yuriyago/events{/privacy}",
                //             "received_events_url": "https://api.github.com/users/yuriyago/received_events",
                //             "type": "User",
                //             "site_admin": false
                //         },
                //         "html_url": "https://github.com/yuriyago/deploy-teste",
                //         "description": null,
                //         "fork": false,
                //         "url": "https://api.github.com/repos/yuriyago/deploy-teste",
                //         "forks_url": "https://api.github.com/repos/yuriyago/deploy-teste/forks",
                //         "keys_url": "https://api.github.com/repos/yuriyago/deploy-teste/keys{/key_id}",
                //         "collaborators_url": "https://api.github.com/repos/yuriyago/deploy-teste/collaborators{/collaborator}",
                //         "teams_url": "https://api.github.com/repos/yuriyago/deploy-teste/teams",
                //         "hooks_url": "https://api.github.com/repos/yuriyago/deploy-teste/hooks",
                //         "issue_events_url": "https://api.github.com/repos/yuriyago/deploy-teste/issues/events{/number}",
                //         "events_url": "https://api.github.com/repos/yuriyago/deploy-teste/events",
                //         "assignees_url": "https://api.github.com/repos/yuriyago/deploy-teste/assignees{/user}",
                //         "branches_url": "https://api.github.com/repos/yuriyago/deploy-teste/branches{/branch}",
                //         "tags_url": "https://api.github.com/repos/yuriyago/deploy-teste/tags",
                //         "blobs_url": "https://api.github.com/repos/yuriyago/deploy-teste/git/blobs{/sha}",
                //         "git_tags_url": "https://api.github.com/repos/yuriyago/deploy-teste/git/tags{/sha}",
                //         "git_refs_url": "https://api.github.com/repos/yuriyago/deploy-teste/git/refs{/sha}",
                //         "trees_url": "https://api.github.com/repos/yuriyago/deploy-teste/git/trees{/sha}",
                //         "statuses_url": "https://api.github.com/repos/yuriyago/deploy-teste/statuses/{sha}",
                //         "languages_url": "https://api.github.com/repos/yuriyago/deploy-teste/languages",
                //         "stargazers_url": "https://api.github.com/repos/yuriyago/deploy-teste/stargazers",
                //         "contributors_url": "https://api.github.com/repos/yuriyago/deploy-teste/contributors",
                //         "subscribers_url": "https://api.github.com/repos/yuriyago/deploy-teste/subscribers",
                //         "subscription_url": "https://api.github.com/repos/yuriyago/deploy-teste/subscription",
                //         "commits_url": "https://api.github.com/repos/yuriyago/deploy-teste/commits{/sha}",
                //         "git_commits_url": "https://api.github.com/repos/yuriyago/deploy-teste/git/commits{/sha}",
                //         "comments_url": "https://api.github.com/repos/yuriyago/deploy-teste/comments{/number}",
                //         "issue_comment_url": "https://api.github.com/repos/yuriyago/deploy-teste/issues/comments{/number}",
                //         "contents_url": "https://api.github.com/repos/yuriyago/deploy-teste/contents/{+path}",
                //         "compare_url": "https://api.github.com/repos/yuriyago/deploy-teste/compare/{base}...{head}",
                //         "merges_url": "https://api.github.com/repos/yuriyago/deploy-teste/merges",
                //         "archive_url": "https://api.github.com/repos/yuriyago/deploy-teste/{archive_format}{/ref}",
                //         "downloads_url": "https://api.github.com/repos/yuriyago/deploy-teste/downloads",
                //         "issues_url": "https://api.github.com/repos/yuriyago/deploy-teste/issues{/number}",
                //         "pulls_url": "https://api.github.com/repos/yuriyago/deploy-teste/pulls{/number}",
                //         "milestones_url": "https://api.github.com/repos/yuriyago/deploy-teste/milestones{/number}",
                //         "notifications_url": "https://api.github.com/repos/yuriyago/deploy-teste/notifications{?since,all,participating}",
                //         "labels_url": "https://api.github.com/repos/yuriyago/deploy-teste/labels{/name}",
                //         "releases_url": "https://api.github.com/repos/yuriyago/deploy-teste/releases{/id}",
                //         "deployments_url": "https://api.github.com/repos/yuriyago/deploy-teste/deployments",
                //         "created_at": "2017-12-01T17:52:26Z",
                //         "updated_at": "2017-12-01T17:57:14Z",
                //         "pushed_at": "2017-12-01T17:57:13Z",
                //         "git_url": "git://github.com/yuriyago/deploy-teste.git",
                //         "ssh_url": "git@github.com:yuriyago/deploy-teste.git",
                //         "clone_url": "https://github.com/yuriyago/deploy-teste.git",
                //         "svn_url": "https://github.com/yuriyago/deploy-teste",
                //         "homepage": null,
                //         "size": 3,
                //         "stargazers_count": 0,
                //         "watchers_count": 0,
                //         "language": "Ruby",
                //         "has_issues": true,
                //         "has_projects": true,
                //         "has_downloads": true,
                //         "has_wiki": true,
                //         "has_pages": false,
                //         "forks_count": 0,
                //         "mirror_url": null,
                //         "archived": false,
                //         "disabled": false,
                //         "open_issues_count": 0,
                //         "license": null,
                //         "forks": 0,
                //         "open_issues": 0,
                //         "watchers": 0,
                //         "default_branch": "master"
                //     },
                //     {
                //         "id": 68557913,
                //         "node_id": "MDEwOlJlcG9zaXRvcnk2ODU1NzkxMw==",
                //         "name": "LP-2016.2",
                //         "full_name": "yuriyago/LP-2016.2",
                //         "private": false,
                //         "owner": {
                //             "login": "yuriyago",
                //             "id": 18572853,
                //             "node_id": "MDQ6VXNlcjE4NTcyODUz",
                //             "avatar_url": "https://avatars2.githubusercontent.com/u/18572853?v=4",
                //             "gravatar_id": "",
                //             "url": "https://api.github.com/users/yuriyago",
                //             "html_url": "https://github.com/yuriyago",
                //             "followers_url": "https://api.github.com/users/yuriyago/followers",
                //             "following_url": "https://api.github.com/users/yuriyago/following{/other_user}",
                //             "gists_url": "https://api.github.com/users/yuriyago/gists{/gist_id}",
                //             "starred_url": "https://api.github.com/users/yuriyago/starred{/owner}{/repo}",
                //             "subscriptions_url": "https://api.github.com/users/yuriyago/subscriptions",
                //             "organizations_url": "https://api.github.com/users/yuriyago/orgs",
                //             "repos_url": "https://api.github.com/users/yuriyago/repos",
                //             "events_url": "https://api.github.com/users/yuriyago/events{/privacy}",
                //             "received_events_url": "https://api.github.com/users/yuriyago/received_events",
                //             "type": "User",
                //             "site_admin": false
                //         },
                //         "html_url": "https://github.com/yuriyago/LP-2016.2",
                //         "description": "Curso de Linguagens de Programação EMAp/FGV",
                //         "fork": true,
                //         "url": "https://api.github.com/repos/yuriyago/LP-2016.2",
                //         "forks_url": "https://api.github.com/repos/yuriyago/LP-2016.2/forks",
                //         "keys_url": "https://api.github.com/repos/yuriyago/LP-2016.2/keys{/key_id}",
                //         "collaborators_url": "https://api.github.com/repos/yuriyago/LP-2016.2/collaborators{/collaborator}",
                //         "teams_url": "https://api.github.com/repos/yuriyago/LP-2016.2/teams",
                //         "hooks_url": "https://api.github.com/repos/yuriyago/LP-2016.2/hooks",
                //         "issue_events_url": "https://api.github.com/repos/yuriyago/LP-2016.2/issues/events{/number}",
                //         "events_url": "https://api.github.com/repos/yuriyago/LP-2016.2/events",
                //         "assignees_url": "https://api.github.com/repos/yuriyago/LP-2016.2/assignees{/user}",
                //         "branches_url": "https://api.github.com/repos/yuriyago/LP-2016.2/branches{/branch}",
                //         "tags_url": "https://api.github.com/repos/yuriyago/LP-2016.2/tags",
                //         "blobs_url": "https://api.github.com/repos/yuriyago/LP-2016.2/git/blobs{/sha}",
                //         "git_tags_url": "https://api.github.com/repos/yuriyago/LP-2016.2/git/tags{/sha}",
                //         "git_refs_url": "https://api.github.com/repos/yuriyago/LP-2016.2/git/refs{/sha}",
                //         "trees_url": "https://api.github.com/repos/yuriyago/LP-2016.2/git/trees{/sha}",
                //         "statuses_url": "https://api.github.com/repos/yuriyago/LP-2016.2/statuses/{sha}",
                //         "languages_url": "https://api.github.com/repos/yuriyago/LP-2016.2/languages",
                //         "stargazers_url": "https://api.github.com/repos/yuriyago/LP-2016.2/stargazers",
                //         "contributors_url": "https://api.github.com/repos/yuriyago/LP-2016.2/contributors",
                //         "subscribers_url": "https://api.github.com/repos/yuriyago/LP-2016.2/subscribers",
                //         "subscription_url": "https://api.github.com/repos/yuriyago/LP-2016.2/subscription",
                //         "commits_url": "https://api.github.com/repos/yuriyago/LP-2016.2/commits{/sha}",
                //         "git_commits_url": "https://api.github.com/repos/yuriyago/LP-2016.2/git/commits{/sha}",
                //         "comments_url": "https://api.github.com/repos/yuriyago/LP-2016.2/comments{/number}",
                //         "issue_comment_url": "https://api.github.com/repos/yuriyago/LP-2016.2/issues/comments{/number}",
                //         "contents_url": "https://api.github.com/repos/yuriyago/LP-2016.2/contents/{+path}",
                //         "compare_url": "https://api.github.com/repos/yuriyago/LP-2016.2/compare/{base}...{head}",
                //         "merges_url": "https://api.github.com/repos/yuriyago/LP-2016.2/merges",
                //         "archive_url": "https://api.github.com/repos/yuriyago/LP-2016.2/{archive_format}{/ref}",
                //         "downloads_url": "https://api.github.com/repos/yuriyago/LP-2016.2/downloads",
                //         "issues_url": "https://api.github.com/repos/yuriyago/LP-2016.2/issues{/number}",
                //         "pulls_url": "https://api.github.com/repos/yuriyago/LP-2016.2/pulls{/number}",
                //         "milestones_url": "https://api.github.com/repos/yuriyago/LP-2016.2/milestones{/number}",
                //         "notifications_url": "https://api.github.com/repos/yuriyago/LP-2016.2/notifications{?since,all,participating}",
                //         "labels_url": "https://api.github.com/repos/yuriyago/LP-2016.2/labels{/name}",
                //         "releases_url": "https://api.github.com/repos/yuriyago/LP-2016.2/releases{/id}",
                //         "deployments_url": "https://api.github.com/repos/yuriyago/LP-2016.2/deployments",
                //         "created_at": "2016-09-19T01:24:01Z",
                //         "updated_at": "2016-09-19T01:24:02Z",
                //         "pushed_at": "2016-12-07T10:30:06Z",
                //         "git_url": "git://github.com/yuriyago/LP-2016.2.git",
                //         "ssh_url": "git@github.com:yuriyago/LP-2016.2.git",
                //         "clone_url": "https://github.com/yuriyago/LP-2016.2.git",
                //         "svn_url": "https://github.com/yuriyago/LP-2016.2",
                //         "homepage": null,
                //         "size": 243,
                //         "stargazers_count": 0,
                //         "watchers_count": 0,
                //         "language": "Racket",
                //         "has_issues": false,
                //         "has_projects": true,
                //         "has_downloads": true,
                //         "has_wiki": true,
                //         "has_pages": false,
                //         "forks_count": 0,
                //         "mirror_url": null,
                //         "archived": false,
                //         "disabled": false,
                //         "open_issues_count": 0,
                //         "license": null,
                //         "forks": 0,
                //         "open_issues": 0,
                //         "watchers": 0,
                //         "default_branch": "master"
                //     }
                // ]
            });
        } catch (error) {
            console.error(error);
        }
    }
}